import { cache } from "react";
import { DEFAULT_EVENT_ID } from "./infrastructure/dynamodb-client";
import { DynamoTeamRepository } from "./infrastructure/repositories/team-repository";
import { DynamoMatchRepository } from "./infrastructure/repositories/match-repository";
import { DynamoBracketRepository } from "./infrastructure/repositories/bracket-repository";
import { DynamoEventRepository } from "./infrastructure/repositories/event-repository";
import { DynamoGroupRepository } from "./infrastructure/repositories/group-repository";
import { DynamoCourtRepository } from "./infrastructure/repositories/court-repository";
import { DynamoCustomLeagueRepository } from "./infrastructure/repositories/custom-league-repository";
import { createGetTeams } from "./usecase/team/get-teams";
import { createGetMatches, createGetMatch } from "./usecase/match/get-matches";
import { createSubmitScore } from "./usecase/match/submit-score";
import { createChangeMatchStatus } from "./usecase/match/change-match-status";
import { createGetStandings } from "./usecase/standings/get-standings";
import { createGetEventTournamentData } from "./usecase/event/get-event-tournament-data";
import { createUpdateEvent } from "./usecase/event/update-event";
import { createVerifyPassword } from "./usecase/auth/verify-password";
import { createSaveGroup } from "./usecase/group/save-group";
import { createDeleteGroup } from "./usecase/group/delete-group";
import { createSaveTeam } from "./usecase/team/save-team";
import { createDeleteTeam } from "./usecase/team/delete-team";
import { createSaveMatch } from "./usecase/match/save-match";
import { createDeleteMatch } from "./usecase/match/delete-match";
import { createSaveBracket } from "./usecase/bracket/save-bracket";
import { createDeleteBracket } from "./usecase/bracket/delete-bracket";
import { createGenerateBrackets } from "./usecase/bracket/generate-brackets";
import { createResolveMatchResults } from "./usecase/bracket/resolve-match-results";
import { createSaveCourt } from "./usecase/court/save-court";
import { createDeleteCourt } from "./usecase/court/delete-court";
import { createSaveCustomLeague } from "./usecase/custom-league/save-custom-league";
import { createDeleteCustomLeague } from "./usecase/custom-league/delete-custom-league";
import { createGetCustomLeagueStandings } from "./usecase/standings/get-custom-league-standings";

// --- Repositories ---
const teamRepo = new DynamoTeamRepository();
const matchRepo = new DynamoMatchRepository();
const bracketRepo = new DynamoBracketRepository();
const eventRepo = new DynamoEventRepository();
const groupRepo = new DynamoGroupRepository();
const courtRepo = new DynamoCourtRepository();
const customLeagueRepo = new DynamoCustomLeagueRepository();

// --- Read (cache で引数ベースのリクエスト単位メモ化) ---
export const getTeams = cache((eid: string) => createGetTeams(teamRepo, eid)());
export const getGroups = cache((eid: string) => groupRepo.findAll(eid));
export const getMatches = cache((eid: string) => createGetMatches(matchRepo, eid)());
export const getMatch = createGetMatch(matchRepo);
export const getBrackets = cache((eid: string) => bracketRepo.findAll(eid));
export const getStandings = cache((eid: string) => createGetStandings(matchRepo, teamRepo, groupRepo, eid)());
export const getEventTournamentData = cache((eid: string) => createGetEventTournamentData(bracketRepo, matchRepo, teamRepo, eid)());
export const getEvent = cache((eid: string) => eventRepo.findById(eid));
export const getCourts = cache((eid: string) => courtRepo.findAll(eid));
export const getCustomLeagues = cache((eid: string) => customLeagueRepo.findAll(eid));
export const getCustomLeagueStandings = cache((eid: string) => createGetCustomLeagueStandings(matchRepo, teamRepo, customLeagueRepo, eid)());

// --- Write ---
export const submitScore = createSubmitScore(matchRepo);
export const changeMatchStatus = createChangeMatchStatus(matchRepo);
export const verifyPassword = (eid: string) => createVerifyPassword(eventRepo, eid);
export const updateEvent = (eid: string) => createUpdateEvent(eventRepo, eid);
export const saveGroup = createSaveGroup(groupRepo);
export const deleteGroup = createDeleteGroup(groupRepo);
export const saveTeam = createSaveTeam(teamRepo);
export const deleteTeam = createDeleteTeam(teamRepo);
export const saveMatch = createSaveMatch(matchRepo);
export const deleteMatch = createDeleteMatch(matchRepo);
export const saveBracket = createSaveBracket(bracketRepo, matchRepo);
export const deleteBracket = createDeleteBracket(bracketRepo, matchRepo);
export const generateBrackets = createGenerateBrackets(bracketRepo, matchRepo);
export const resolveMatchResults = createResolveMatchResults(bracketRepo, matchRepo, teamRepo, groupRepo);
export const saveCourt = createSaveCourt(courtRepo);
export const deleteCourt = createDeleteCourt(courtRepo);
export const saveCustomLeague = createSaveCustomLeague(customLeagueRepo);
export const deleteCustomLeague = createDeleteCustomLeague(customLeagueRepo);
export { DEFAULT_EVENT_ID };
